name: Build and Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Setup environment variables
        uses: npm run setup:prod

      - name: Build project
        run: npm run build

      # - name: Upload production-ready build files
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: production-files
      #     path: ./dist

  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      # - name: 🚚 Get latest code
      #   uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist
          server-dir: public_html/
  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: production-files
  #         path: ./dist

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist