name: Build and Deploy

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Setup environment variables
        run: npm run setup:prod

      - name: Build project
        run: npm run build

  deploy:
    name: 🎉 Deploy
    needs: build
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: check dist folder
          run: ls -a
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: public_html/
